// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// tcov_cpp
arma::mat tcov_cpp(const arma::mat& x, const double& beta);
RcppExport SEXP _ICSClust_tcov_cpp(SEXP xSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double& >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(tcov_cpp(x, beta));
    return rcpp_result_gen;
END_RCPP
}
// scov_cpp
arma::mat scov_cpp(const arma::mat& x, const arma::vec& m, const arma::mat& S_inv, const double& beta);
RcppExport SEXP _ICSClust_scov_cpp(SEXP xSEXP, SEXP mSEXP, SEXP S_invSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S_inv(S_invSEXP);
    Rcpp::traits::input_parameter< const double& >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(scov_cpp(x, m, S_inv, beta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ICSClust_tcov_cpp", (DL_FUNC) &_ICSClust_tcov_cpp, 2},
    {"_ICSClust_scov_cpp", (DL_FUNC) &_ICSClust_scov_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_ICSClust(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
