# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tcov_cpp <- function(x, beta) {
    .Call(`_ICSClust_tcov_cpp`, x, beta)
}

scov_cpp <- function(x, m, S_inv, beta) {
    .Call(`_ICSClust_scov_cpp`, x, m, S_inv, beta)
}

